// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// User represents an XYZ user.
type User struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Firstname            string   `protobuf:"bytes,3,opt,name=firstname,proto3" json:"firstname,omitempty"`
	Lastname             string   `protobuf:"bytes,4,opt,name=lastname,proto3" json:"lastname,omitempty"`
	CreatedAt            int64    `protobuf:"varint,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            int64    `protobuf:"varint,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{0}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetFirstname() string {
	if m != nil {
		return m.Firstname
	}
	return ""
}

func (m *User) GetLastname() string {
	if m != nil {
		return m.Lastname
	}
	return ""
}

func (m *User) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *User) GetUpdatedAt() int64 {
	if m != nil {
		return m.UpdatedAt
	}
	return 0
}

// CreateUserRequest contains all the fields for creating a user.
type CreateUserRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Firstname            string   `protobuf:"bytes,3,opt,name=firstname,proto3" json:"firstname,omitempty"`
	Lastname             string   `protobuf:"bytes,4,opt,name=lastname,proto3" json:"lastname,omitempty"`
	ApiToken             string   `protobuf:"bytes,5,opt,name=api_token,json=apiToken,proto3" json:"api_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateUserRequest) Reset()         { *m = CreateUserRequest{} }
func (m *CreateUserRequest) String() string { return proto.CompactTextString(m) }
func (*CreateUserRequest) ProtoMessage()    {}
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{1}
}

func (m *CreateUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserRequest.Unmarshal(m, b)
}
func (m *CreateUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserRequest.Marshal(b, m, deterministic)
}
func (m *CreateUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserRequest.Merge(m, src)
}
func (m *CreateUserRequest) XXX_Size() int {
	return xxx_messageInfo_CreateUserRequest.Size(m)
}
func (m *CreateUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserRequest proto.InternalMessageInfo

func (m *CreateUserRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *CreateUserRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *CreateUserRequest) GetFirstname() string {
	if m != nil {
		return m.Firstname
	}
	return ""
}

func (m *CreateUserRequest) GetLastname() string {
	if m != nil {
		return m.Lastname
	}
	return ""
}

func (m *CreateUserRequest) GetApiToken() string {
	if m != nil {
		return m.ApiToken
	}
	return ""
}

// ProjectDevice represents a device added to a project.
type ProjectDevice struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AddedBy              string   `protobuf:"bytes,2,opt,name=added_by,json=addedBy,proto3" json:"added_by,omitempty"`
	AddedAt              string   `protobuf:"bytes,3,opt,name=added_at,json=addedAt,proto3" json:"added_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProjectDevice) Reset()         { *m = ProjectDevice{} }
func (m *ProjectDevice) String() string { return proto.CompactTextString(m) }
func (*ProjectDevice) ProtoMessage()    {}
func (*ProjectDevice) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{2}
}

func (m *ProjectDevice) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProjectDevice.Unmarshal(m, b)
}
func (m *ProjectDevice) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProjectDevice.Marshal(b, m, deterministic)
}
func (m *ProjectDevice) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProjectDevice.Merge(m, src)
}
func (m *ProjectDevice) XXX_Size() int {
	return xxx_messageInfo_ProjectDevice.Size(m)
}
func (m *ProjectDevice) XXX_DiscardUnknown() {
	xxx_messageInfo_ProjectDevice.DiscardUnknown(m)
}

var xxx_messageInfo_ProjectDevice proto.InternalMessageInfo

func (m *ProjectDevice) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ProjectDevice) GetAddedBy() string {
	if m != nil {
		return m.AddedBy
	}
	return ""
}

func (m *ProjectDevice) GetAddedAt() string {
	if m != nil {
		return m.AddedAt
	}
	return ""
}

// CreateProjectRequest contains all the fields for creating a project.
type CreateProjectRequest struct {
	ApiToken string `protobuf:"bytes,1,opt,name=api_token,json=apiToken,proto3" json:"api_token,omitempty"`
	// TODO: user a map for contributors and devices to avoid duplicates
	Contributors         []string `protobuf:"bytes,2,rep,name=contributors,proto3" json:"contributors,omitempty"`
	Devices              []string `protobuf:"bytes,3,rep,name=devices,proto3" json:"devices,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateProjectRequest) Reset()         { *m = CreateProjectRequest{} }
func (m *CreateProjectRequest) String() string { return proto.CompactTextString(m) }
func (*CreateProjectRequest) ProtoMessage()    {}
func (*CreateProjectRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{3}
}

func (m *CreateProjectRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateProjectRequest.Unmarshal(m, b)
}
func (m *CreateProjectRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateProjectRequest.Marshal(b, m, deterministic)
}
func (m *CreateProjectRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateProjectRequest.Merge(m, src)
}
func (m *CreateProjectRequest) XXX_Size() int {
	return xxx_messageInfo_CreateProjectRequest.Size(m)
}
func (m *CreateProjectRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateProjectRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateProjectRequest proto.InternalMessageInfo

func (m *CreateProjectRequest) GetApiToken() string {
	if m != nil {
		return m.ApiToken
	}
	return ""
}

func (m *CreateProjectRequest) GetContributors() []string {
	if m != nil {
		return m.Contributors
	}
	return nil
}

func (m *CreateProjectRequest) GetDevices() []string {
	if m != nil {
		return m.Devices
	}
	return nil
}

// Project represents an XYZ project.
type Project struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatorId            string   `protobuf:"bytes,2,opt,name=creator_id,json=creatorId,proto3" json:"creator_id,omitempty"`
	Contributors         []string `protobuf:"bytes,3,rep,name=contributors,proto3" json:"contributors,omitempty"`
	Devices              []string `protobuf:"bytes,4,rep,name=devices,proto3" json:"devices,omitempty"`
	CreatedAt            int64    `protobuf:"varint,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            int64    `protobuf:"varint,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Project) Reset()         { *m = Project{} }
func (m *Project) String() string { return proto.CompactTextString(m) }
func (*Project) ProtoMessage()    {}
func (*Project) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{4}
}

func (m *Project) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Project.Unmarshal(m, b)
}
func (m *Project) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Project.Marshal(b, m, deterministic)
}
func (m *Project) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Project.Merge(m, src)
}
func (m *Project) XXX_Size() int {
	return xxx_messageInfo_Project.Size(m)
}
func (m *Project) XXX_DiscardUnknown() {
	xxx_messageInfo_Project.DiscardUnknown(m)
}

var xxx_messageInfo_Project proto.InternalMessageInfo

func (m *Project) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Project) GetCreatorId() string {
	if m != nil {
		return m.CreatorId
	}
	return ""
}

func (m *Project) GetContributors() []string {
	if m != nil {
		return m.Contributors
	}
	return nil
}

func (m *Project) GetDevices() []string {
	if m != nil {
		return m.Devices
	}
	return nil
}

func (m *Project) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *Project) GetUpdatedAt() int64 {
	if m != nil {
		return m.UpdatedAt
	}
	return 0
}

// ProjectsList is a list of projects.
type ProjectsList struct {
	List                 []*Project `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ProjectsList) Reset()         { *m = ProjectsList{} }
func (m *ProjectsList) String() string { return proto.CompactTextString(m) }
func (*ProjectsList) ProtoMessage()    {}
func (*ProjectsList) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{5}
}

func (m *ProjectsList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProjectsList.Unmarshal(m, b)
}
func (m *ProjectsList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProjectsList.Marshal(b, m, deterministic)
}
func (m *ProjectsList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProjectsList.Merge(m, src)
}
func (m *ProjectsList) XXX_Size() int {
	return xxx_messageInfo_ProjectsList.Size(m)
}
func (m *ProjectsList) XXX_DiscardUnknown() {
	xxx_messageInfo_ProjectsList.DiscardUnknown(m)
}

var xxx_messageInfo_ProjectsList proto.InternalMessageInfo

func (m *ProjectsList) GetList() []*Project {
	if m != nil {
		return m.List
	}
	return nil
}

// Device represents a device that can be used in one or more projects.
type Device struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Description          string   `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Device) Reset()         { *m = Device{} }
func (m *Device) String() string { return proto.CompactTextString(m) }
func (*Device) ProtoMessage()    {}
func (*Device) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{6}
}

func (m *Device) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Device.Unmarshal(m, b)
}
func (m *Device) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Device.Marshal(b, m, deterministic)
}
func (m *Device) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Device.Merge(m, src)
}
func (m *Device) XXX_Size() int {
	return xxx_messageInfo_Device.Size(m)
}
func (m *Device) XXX_DiscardUnknown() {
	xxx_messageInfo_Device.DiscardUnknown(m)
}

var xxx_messageInfo_Device proto.InternalMessageInfo

func (m *Device) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Device) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

// DevicesList is a list of devices.
type DevicesList struct {
	Devices              []string `protobuf:"bytes,1,rep,name=devices,proto3" json:"devices,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DevicesList) Reset()         { *m = DevicesList{} }
func (m *DevicesList) String() string { return proto.CompactTextString(m) }
func (*DevicesList) ProtoMessage()    {}
func (*DevicesList) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{7}
}

func (m *DevicesList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DevicesList.Unmarshal(m, b)
}
func (m *DevicesList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DevicesList.Marshal(b, m, deterministic)
}
func (m *DevicesList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DevicesList.Merge(m, src)
}
func (m *DevicesList) XXX_Size() int {
	return xxx_messageInfo_DevicesList.Size(m)
}
func (m *DevicesList) XXX_DiscardUnknown() {
	xxx_messageInfo_DevicesList.DiscardUnknown(m)
}

var xxx_messageInfo_DevicesList proto.InternalMessageInfo

func (m *DevicesList) GetDevices() []string {
	if m != nil {
		return m.Devices
	}
	return nil
}

// AddProjectContributorsRequest contains
// a list of contributors to add to a project.
type AddProjectContributorsRequest struct {
	ProjectId            string   `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	Contributors         []string `protobuf:"bytes,2,rep,name=contributors,proto3" json:"contributors,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddProjectContributorsRequest) Reset()         { *m = AddProjectContributorsRequest{} }
func (m *AddProjectContributorsRequest) String() string { return proto.CompactTextString(m) }
func (*AddProjectContributorsRequest) ProtoMessage()    {}
func (*AddProjectContributorsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{8}
}

func (m *AddProjectContributorsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddProjectContributorsRequest.Unmarshal(m, b)
}
func (m *AddProjectContributorsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddProjectContributorsRequest.Marshal(b, m, deterministic)
}
func (m *AddProjectContributorsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddProjectContributorsRequest.Merge(m, src)
}
func (m *AddProjectContributorsRequest) XXX_Size() int {
	return xxx_messageInfo_AddProjectContributorsRequest.Size(m)
}
func (m *AddProjectContributorsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddProjectContributorsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddProjectContributorsRequest proto.InternalMessageInfo

func (m *AddProjectContributorsRequest) GetProjectId() string {
	if m != nil {
		return m.ProjectId
	}
	return ""
}

func (m *AddProjectContributorsRequest) GetContributors() []string {
	if m != nil {
		return m.Contributors
	}
	return nil
}

// AddProjectDevicesRequest contains
// a list of devices to add to a project.
type AddProjectDevicesRequest struct {
	ProjectId            string   `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	Devices              []string `protobuf:"bytes,2,rep,name=devices,proto3" json:"devices,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddProjectDevicesRequest) Reset()         { *m = AddProjectDevicesRequest{} }
func (m *AddProjectDevicesRequest) String() string { return proto.CompactTextString(m) }
func (*AddProjectDevicesRequest) ProtoMessage()    {}
func (*AddProjectDevicesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{9}
}

func (m *AddProjectDevicesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddProjectDevicesRequest.Unmarshal(m, b)
}
func (m *AddProjectDevicesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddProjectDevicesRequest.Marshal(b, m, deterministic)
}
func (m *AddProjectDevicesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddProjectDevicesRequest.Merge(m, src)
}
func (m *AddProjectDevicesRequest) XXX_Size() int {
	return xxx_messageInfo_AddProjectDevicesRequest.Size(m)
}
func (m *AddProjectDevicesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddProjectDevicesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddProjectDevicesRequest proto.InternalMessageInfo

func (m *AddProjectDevicesRequest) GetProjectId() string {
	if m != nil {
		return m.ProjectId
	}
	return ""
}

func (m *AddProjectDevicesRequest) GetDevices() []string {
	if m != nil {
		return m.Devices
	}
	return nil
}

// GetProjectDevicesRequest contains the
// project ID whose devices will be returned.
type GetProjectDevicesRequest struct {
	ProjectId            string   `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetProjectDevicesRequest) Reset()         { *m = GetProjectDevicesRequest{} }
func (m *GetProjectDevicesRequest) String() string { return proto.CompactTextString(m) }
func (*GetProjectDevicesRequest) ProtoMessage()    {}
func (*GetProjectDevicesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{10}
}

func (m *GetProjectDevicesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetProjectDevicesRequest.Unmarshal(m, b)
}
func (m *GetProjectDevicesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetProjectDevicesRequest.Marshal(b, m, deterministic)
}
func (m *GetProjectDevicesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetProjectDevicesRequest.Merge(m, src)
}
func (m *GetProjectDevicesRequest) XXX_Size() int {
	return xxx_messageInfo_GetProjectDevicesRequest.Size(m)
}
func (m *GetProjectDevicesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetProjectDevicesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetProjectDevicesRequest proto.InternalMessageInfo

func (m *GetProjectDevicesRequest) GetProjectId() string {
	if m != nil {
		return m.ProjectId
	}
	return ""
}

func init() {
	proto.RegisterType((*User)(nil), "api.User")
	proto.RegisterType((*CreateUserRequest)(nil), "api.CreateUserRequest")
	proto.RegisterType((*ProjectDevice)(nil), "api.ProjectDevice")
	proto.RegisterType((*CreateProjectRequest)(nil), "api.CreateProjectRequest")
	proto.RegisterType((*Project)(nil), "api.Project")
	proto.RegisterType((*ProjectsList)(nil), "api.ProjectsList")
	proto.RegisterType((*Device)(nil), "api.Device")
	proto.RegisterType((*DevicesList)(nil), "api.DevicesList")
	proto.RegisterType((*AddProjectContributorsRequest)(nil), "api.AddProjectContributorsRequest")
	proto.RegisterType((*AddProjectDevicesRequest)(nil), "api.AddProjectDevicesRequest")
	proto.RegisterType((*GetProjectDevicesRequest)(nil), "api.GetProjectDevicesRequest")
}

func init() { proto.RegisterFile("api.proto", fileDescriptor_00212fb1f9d3bf1c) }

var fileDescriptor_00212fb1f9d3bf1c = []byte{
	// 693 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x54, 0xcd, 0x6e, 0xd3, 0x4c,
	0x14, 0xd5, 0xc4, 0x69, 0x13, 0xdf, 0xb4, 0x5f, 0xbf, 0x8e, 0x4a, 0x71, 0xdd, 0x46, 0x8a, 0x46,
	0x20, 0xa2, 0x2c, 0x92, 0xaa, 0x88, 0x05, 0xdd, 0xa5, 0x05, 0x55, 0x08, 0xa4, 0xa2, 0x40, 0xf9,
	0xe9, 0x26, 0x9a, 0x64, 0xa6, 0xd5, 0x40, 0x6a, 0x4f, 0x3d, 0x13, 0x50, 0x05, 0x6c, 0xd8, 0xb2,
	0x64, 0xcb, 0x12, 0xf1, 0x04, 0xbc, 0x09, 0xaf, 0xc0, 0x83, 0x20, 0x8f, 0xc7, 0xb1, 0xdd, 0x34,
	0x11, 0xa2, 0xcb, 0x7b, 0x8f, 0x7d, 0xce, 0xb9, 0x7f, 0x03, 0x2e, 0x95, 0xa2, 0x2d, 0xa3, 0x50,
	0x87, 0xd8, 0xa1, 0x52, 0xf8, 0x5b, 0xa7, 0x61, 0x78, 0x3a, 0xe2, 0x1d, 0x2a, 0x45, 0x87, 0x06,
	0x41, 0xa8, 0xa9, 0x16, 0x61, 0xa0, 0x92, 0x4f, 0xfc, 0x4d, 0x8b, 0x9a, 0x68, 0x30, 0x3e, 0xe9,
	0xf0, 0x33, 0xa9, 0x2f, 0x12, 0x90, 0x7c, 0x47, 0x50, 0x3e, 0x52, 0x3c, 0xc2, 0xff, 0x41, 0x49,
	0x30, 0x0f, 0x35, 0x50, 0xd3, 0xed, 0x95, 0x04, 0xc3, 0x6b, 0xb0, 0xc0, 0xcf, 0xa8, 0x18, 0x79,
	0x25, 0x93, 0x4a, 0x02, 0xbc, 0x05, 0xee, 0x89, 0x88, 0x94, 0x0e, 0xe8, 0x19, 0xf7, 0x1c, 0x83,
	0x64, 0x09, 0xec, 0x43, 0x75, 0x44, 0x2d, 0x58, 0x36, 0xe0, 0x24, 0xc6, 0x75, 0x80, 0x61, 0xc4,
	0xa9, 0xe6, 0xac, 0x4f, 0xb5, 0xb7, 0xd0, 0x40, 0x4d, 0xa7, 0xe7, 0xda, 0x4c, 0x57, 0xc7, 0xf0,
	0x58, 0xb2, 0x14, 0x5e, 0x4c, 0x60, 0x9b, 0xe9, 0x6a, 0xf2, 0x0d, 0xc1, 0xea, 0xbe, 0xf9, 0x38,
	0x36, 0xdb, 0xe3, 0xe7, 0x63, 0xae, 0x74, 0xe6, 0x11, 0xe5, 0x3d, 0xfa, 0x50, 0x95, 0x54, 0xa9,
	0xf7, 0x61, 0xc4, 0xac, 0xf9, 0x49, 0x7c, 0x0d, 0xff, 0x9b, 0xa6, 0xeb, 0x7d, 0x1d, 0xbe, 0xe5,
	0x81, 0xb1, 0xef, 0xf6, 0xaa, 0x54, 0x8a, 0xe7, 0x71, 0x4c, 0x8e, 0x60, 0xf9, 0x69, 0x14, 0xbe,
	0xe1, 0x43, 0xfd, 0x80, 0xbf, 0x13, 0x43, 0x3e, 0xd5, 0xcd, 0x0d, 0xa8, 0x52, 0xc6, 0x38, 0xeb,
	0x0f, 0x2e, 0xac, 0xa7, 0x8a, 0x89, 0xf7, 0x2e, 0x32, 0x88, 0x6a, 0xeb, 0x28, 0x81, 0xba, 0x9a,
	0x9c, 0xc3, 0x5a, 0x52, 0xb4, 0x25, 0x4f, 0xeb, 0x2e, 0x78, 0x41, 0x45, 0x2f, 0x98, 0xc0, 0xd2,
	0x30, 0x0c, 0x74, 0x24, 0x06, 0x63, 0x1d, 0x46, 0xca, 0x2b, 0x35, 0x9c, 0xa6, 0xdb, 0x2b, 0xe4,
	0xb0, 0x07, 0x15, 0x66, 0x8c, 0x2a, 0xcf, 0x31, 0x70, 0x1a, 0x92, 0x9f, 0x08, 0x2a, 0x56, 0x6d,
	0xaa, 0x88, 0x74, 0x84, 0x61, 0xd4, 0x17, 0x69, 0x6b, 0x5d, 0x9b, 0x79, 0xc4, 0xa6, 0x84, 0x9d,
	0xf9, 0xc2, 0xe5, 0x82, 0xf0, 0x35, 0xf7, 0x63, 0x1b, 0x96, 0xac, 0x6b, 0xf5, 0x44, 0x28, 0x8d,
	0x1b, 0x50, 0x1e, 0x09, 0xa5, 0x3d, 0xd4, 0x70, 0x9a, 0xb5, 0x9d, 0xa5, 0x76, 0x7c, 0x30, 0x69,
	0x13, 0x0d, 0x42, 0x76, 0x61, 0x71, 0xc6, 0xac, 0x1a, 0x50, 0x63, 0x5c, 0x0d, 0x23, 0x21, 0xe3,
	0x2b, 0xb2, 0x75, 0xe6, 0x53, 0xe4, 0x0e, 0xd4, 0x92, 0x7f, 0x13, 0xb1, 0x5c, 0x51, 0xa8, 0xd8,
	0xcd, 0x01, 0xd4, 0xbb, 0x8c, 0x59, 0xe1, 0xfd, 0x5c, 0x23, 0xd2, 0x49, 0xd6, 0x01, 0x64, 0x82,
	0xf6, 0x27, 0x1e, 0x5c, 0x9b, 0xb9, 0xa2, 0xa5, 0x57, 0xcc, 0x92, 0x3c, 0x03, 0x2f, 0xd3, 0xb0,
	0xb6, 0xfe, 0x92, 0x3e, 0x67, 0xbc, 0x54, 0x34, 0x7e, 0x1f, 0xbc, 0x03, 0xae, 0xff, 0x85, 0x74,
	0xe7, 0x05, 0x54, 0x0e, 0x25, 0x0f, 0x5e, 0xbd, 0x3e, 0xc6, 0x8f, 0x01, 0xb2, 0xa3, 0xc5, 0xeb,
	0x66, 0x0a, 0x53, 0x57, 0xec, 0xbb, 0x26, 0x1f, 0x67, 0x88, 0xff, 0xf9, 0xd7, 0xef, 0xaf, 0xa5,
	0x35, 0xb2, 0x62, 0x9e, 0xb2, 0xe1, 0xe4, 0xd3, 0x5d, 0xd4, 0xda, 0xf9, 0x51, 0x06, 0x27, 0x26,
	0x7d, 0x09, 0xcb, 0x85, 0xa3, 0xc0, 0x1b, 0x39, 0xde, 0xe2, 0xa1, 0xf8, 0x85, 0xc1, 0x93, 0xba,
	0x61, 0xbf, 0x49, 0x70, 0x8e, 0xdd, 0x62, 0xbb, 0xa8, 0x85, 0x0f, 0xa1, 0x96, 0xd5, 0xac, 0xf0,
	0x7a, 0x3b, 0x79, 0x37, 0xdb, 0xe9, 0xbb, 0xd9, 0x7e, 0x18, 0xbf, 0x9b, 0xfe, 0x6a, 0x9e, 0xd3,
	0x2c, 0x00, 0xb9, 0x61, 0x88, 0x57, 0xf0, 0xb2, 0x21, 0x96, 0x29, 0xc3, 0x17, 0x04, 0xeb, 0x57,
	0x8f, 0x1f, 0x13, 0x43, 0x32, 0x77, 0x37, 0xfc, 0x19, 0x06, 0xc8, 0x3d, 0xa3, 0xd6, 0x21, 0xad,
	0x82, 0x5a, 0xe7, 0x43, 0x36, 0x94, 0x4f, 0x1d, 0xca, 0x58, 0x9e, 0x32, 0x2e, 0xef, 0x23, 0xac,
	0x4e, 0xed, 0x09, 0xae, 0x5f, 0xf2, 0x51, 0x1c, 0xf5, 0x4c, 0x0b, 0xdb, 0xc6, 0x42, 0x8b, 0xdc,
	0x9e, 0x6f, 0xc1, 0xb2, 0xc5, 0xea, 0x02, 0xe0, 0x80, 0x5f, 0x92, 0x9d, 0xb5, 0x61, 0xfe, 0xff,
	0x06, 0xce, 0x9d, 0x18, 0x69, 0x19, 0xc1, 0x5b, 0x98, 0xcc, 0x11, 0xb4, 0xbb, 0xbb, 0x57, 0x3e,
	0x2e, 0xc9, 0xc1, 0x60, 0xd1, 0x58, 0xbe, 0xfb, 0x27, 0x00, 0x00, 0xff, 0xff, 0x36, 0x75, 0xbc,
	0x0d, 0x2c, 0x07, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// OpenXYZClient is the client API for OpenXYZ service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type OpenXYZClient interface {
	// CreateUser creates a user.
	CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*User, error)
}

type openXYZClient struct {
	cc *grpc.ClientConn
}

func NewOpenXYZClient(cc *grpc.ClientConn) OpenXYZClient {
	return &openXYZClient{cc}
}

func (c *openXYZClient) CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*User, error) {
	out := new(User)
	err := c.cc.Invoke(ctx, "/api.OpenXYZ/CreateUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OpenXYZServer is the server API for OpenXYZ service.
type OpenXYZServer interface {
	// CreateUser creates a user.
	CreateUser(context.Context, *CreateUserRequest) (*User, error)
}

// UnimplementedOpenXYZServer can be embedded to have forward compatible implementations.
type UnimplementedOpenXYZServer struct {
}

func (*UnimplementedOpenXYZServer) CreateUser(ctx context.Context, req *CreateUserRequest) (*User, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateUser not implemented")
}

func RegisterOpenXYZServer(s *grpc.Server, srv OpenXYZServer) {
	s.RegisterService(&_OpenXYZ_serviceDesc, srv)
}

func _OpenXYZ_CreateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OpenXYZServer).CreateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.OpenXYZ/CreateUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OpenXYZServer).CreateUser(ctx, req.(*CreateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _OpenXYZ_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.OpenXYZ",
	HandlerType: (*OpenXYZServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateUser",
			Handler:    _OpenXYZ_CreateUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api.proto",
}

// XYZClient is the client API for XYZ service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type XYZClient interface {
	// CreateProject creates a project.
	CreateProject(ctx context.Context, in *CreateProjectRequest, opts ...grpc.CallOption) (*Project, error)
	// GetProjects returns the list of projects.
	GetProjects(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*ProjectsList, error)
	// AddProjectContributors adds one or more contributors to a project.
	AddProjectContributors(ctx context.Context, in *AddProjectContributorsRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	// AddProjectDevices adds one or more devices to a project.
	AddProjectDevices(ctx context.Context, in *AddProjectDevicesRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	// GetDevices returns the list of devices assigned to a project.
	GetDevices(ctx context.Context, in *GetProjectDevicesRequest, opts ...grpc.CallOption) (*DevicesList, error)
}

type xYZClient struct {
	cc *grpc.ClientConn
}

func NewXYZClient(cc *grpc.ClientConn) XYZClient {
	return &xYZClient{cc}
}

func (c *xYZClient) CreateProject(ctx context.Context, in *CreateProjectRequest, opts ...grpc.CallOption) (*Project, error) {
	out := new(Project)
	err := c.cc.Invoke(ctx, "/api.XYZ/CreateProject", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *xYZClient) GetProjects(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*ProjectsList, error) {
	out := new(ProjectsList)
	err := c.cc.Invoke(ctx, "/api.XYZ/GetProjects", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *xYZClient) AddProjectContributors(ctx context.Context, in *AddProjectContributorsRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/api.XYZ/AddProjectContributors", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *xYZClient) AddProjectDevices(ctx context.Context, in *AddProjectDevicesRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/api.XYZ/AddProjectDevices", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *xYZClient) GetDevices(ctx context.Context, in *GetProjectDevicesRequest, opts ...grpc.CallOption) (*DevicesList, error) {
	out := new(DevicesList)
	err := c.cc.Invoke(ctx, "/api.XYZ/GetDevices", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// XYZServer is the server API for XYZ service.
type XYZServer interface {
	// CreateProject creates a project.
	CreateProject(context.Context, *CreateProjectRequest) (*Project, error)
	// GetProjects returns the list of projects.
	GetProjects(context.Context, *empty.Empty) (*ProjectsList, error)
	// AddProjectContributors adds one or more contributors to a project.
	AddProjectContributors(context.Context, *AddProjectContributorsRequest) (*empty.Empty, error)
	// AddProjectDevices adds one or more devices to a project.
	AddProjectDevices(context.Context, *AddProjectDevicesRequest) (*empty.Empty, error)
	// GetDevices returns the list of devices assigned to a project.
	GetDevices(context.Context, *GetProjectDevicesRequest) (*DevicesList, error)
}

// UnimplementedXYZServer can be embedded to have forward compatible implementations.
type UnimplementedXYZServer struct {
}

func (*UnimplementedXYZServer) CreateProject(ctx context.Context, req *CreateProjectRequest) (*Project, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateProject not implemented")
}
func (*UnimplementedXYZServer) GetProjects(ctx context.Context, req *empty.Empty) (*ProjectsList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProjects not implemented")
}
func (*UnimplementedXYZServer) AddProjectContributors(ctx context.Context, req *AddProjectContributorsRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddProjectContributors not implemented")
}
func (*UnimplementedXYZServer) AddProjectDevices(ctx context.Context, req *AddProjectDevicesRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddProjectDevices not implemented")
}
func (*UnimplementedXYZServer) GetDevices(ctx context.Context, req *GetProjectDevicesRequest) (*DevicesList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDevices not implemented")
}

func RegisterXYZServer(s *grpc.Server, srv XYZServer) {
	s.RegisterService(&_XYZ_serviceDesc, srv)
}

func _XYZ_CreateProject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateProjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(XYZServer).CreateProject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.XYZ/CreateProject",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(XYZServer).CreateProject(ctx, req.(*CreateProjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _XYZ_GetProjects_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(XYZServer).GetProjects(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.XYZ/GetProjects",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(XYZServer).GetProjects(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _XYZ_AddProjectContributors_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddProjectContributorsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(XYZServer).AddProjectContributors(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.XYZ/AddProjectContributors",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(XYZServer).AddProjectContributors(ctx, req.(*AddProjectContributorsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _XYZ_AddProjectDevices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddProjectDevicesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(XYZServer).AddProjectDevices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.XYZ/AddProjectDevices",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(XYZServer).AddProjectDevices(ctx, req.(*AddProjectDevicesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _XYZ_GetDevices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProjectDevicesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(XYZServer).GetDevices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.XYZ/GetDevices",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(XYZServer).GetDevices(ctx, req.(*GetProjectDevicesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _XYZ_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.XYZ",
	HandlerType: (*XYZServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateProject",
			Handler:    _XYZ_CreateProject_Handler,
		},
		{
			MethodName: "GetProjects",
			Handler:    _XYZ_GetProjects_Handler,
		},
		{
			MethodName: "AddProjectContributors",
			Handler:    _XYZ_AddProjectContributors_Handler,
		},
		{
			MethodName: "AddProjectDevices",
			Handler:    _XYZ_AddProjectDevices_Handler,
		},
		{
			MethodName: "GetDevices",
			Handler:    _XYZ_GetDevices_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api.proto",
}
